file:
  storage:
    path: /Users/pondmakers/Desktop/clean-files

spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

server:
  tomcat:
    max-swallow-size: -1